### ISSUE TITLE
Typo in README.org?

### ISSUE THREAD

**Issue by dr-scsi** [rainstormstudio/nerd-icons-dired#15]
Line 19 in `README.org` reads:

https://github.com/rainstormstudio/nerd-icons-dired/blob/4a068884bf86647d242c3adc8320cd603e15dac3/README.org?plain=1#L19-L23

Looking at the example, I wonder how `straight` fits?  Maybe you meant `use-package`?

**Comment by rainstormstudio** [comment]
Nice observation :) I just fixed it.
