### ISSUE TITLE
Tab `\t` character overlayed with the icons even `whitespace-mode` has been turned off.

### ISSUE THREAD

**Issue by milanglacier** [rainstormstudio/nerd-icons-dired#2]
example setup:

```lisp
(require 'package)
(setq package-user-dir "~/Downloads/emacs-package-dir")

(setq package-list nil)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
(package-initialize)

(add-to-list 'load-path "~/Downloads/open-project-fork/nerd-icons.el")
(add-to-list 'load-path "~/Downloads/open-project-fork/nerd-icons-dired")

(unless package-archive-contents
  (package-refresh-contents))

(dolist (package package-list)
  (unless (package-installed-p package)
    (package-install package)))

(require 'nerd-icons)
(require 'nerd-icons-dired)

(setq whitespace-style '(face tabs tab-mark trailing))


(global-whitespace-mode)

(add-hook 'dired-mode-hook #'nerd-icons-dired-mode)
(add-hook 'dired-mode-hook (lambda () (whitespace-mode -1)))



(load-theme 'modus-operandi t)

```

open emacs, and `C-x d` open any dired directory, here's the screenshot:

<img width="652" alt="Screen Shot 2023-04-22 at 01 04 52" src="https://user-images.githubusercontent.com/45728125/233763791-3117e3ab-6612-4230-a7b5-352daf3c0b1d.png">

Even though the whitespace mode has been turned off, but those weird signs (indicating tabs) between filename and icons are still there.

However, after the dired buffer has been opened, and displayed in the window, `M-x whitespace-mode RET M-x whitespace-mode RET`, i.e. calling this function interactively twice will make the dired buffer display normally:

<img width="807" alt="Screen Shot 2023-04-21 at 21 13 28" src="https://user-images.githubusercontent.com/45728125/233754008-be4a15f0-c340-4f81-861f-65927caa4cd2.png">

I think this is because the icon overlay inserts `\t` between the icons and the filenames.

To be honest, I don't think this is the bug of nerd-icons, instead it is the bug of dired itself regardless of whether `nerd-icons-mode` is enabled or not.

The only thing that matters here is that the sign indicating tab `\t` overlays with the icons.

If we want a dead-brain solution, we can offer the user choices of what characters to be inserted between filename and icons. If I just use spaces instead of tab, then the problem doesn't exist for me.

**Comment by milanglacier** [comment]
I think this is because the icon overlay inserts \t between the icons and the filenames.

To be honest, I don't think this is the bug of nerd-icons, instead it is the bug of dired itself regardless of whether nerd-icons-mode is enabled or not.

The only thing that matters here is that the sign indicating tab \t overlays with the icons.

If we want a dead-brain solution, we can offer the user choices of what characters to be inserted between filename and icons. If I just use spaces instead of tab, then the problem doesn't exist for me.

**Comment by milanglacier** [comment]
change `(add-hook 'dired-mode-hook (lambda () (whitespace-mode -1)))` to `(add-hook 'dired-mode-hook #'whitespace-turn-off)` solves the issue.

**Comment by rainstormstudio** [comment]
I now use `insert` instead of overlays now: 84831dbd1c61167d8e0ccfa7a152f3aefa40406f

Could you please check if this fixes your issue?

**Comment by milanglacier** [comment]
> I now use `insert` instead of overlays now: [84831db](https://github.com/rainstormstudio/nerd-icons-dired/commit/84831dbd1c61167d8e0ccfa7a152f3aefa40406f)
> 
> Could you please check if this fixes your issue?

No, this doesn't help.

In fact this brings other questions and I suggest we revert to previous version.

The new commit makes it not compatible with `wdired-mode`, here is the screenshot after finishing editing of wdired mode, you can see the icons are populated twice.

I am currently turning off `global-white-space-mode` and only activate `whitespace-mode` on text mode and prog mode as workaround. 

<img width="684" alt="Screen Shot 2023-04-26 at 20 34 16" src="https://user-images.githubusercontent.com/45728125/234730610-87bab8e1-1927-4d77-86e6-fcdf672f308c.png">

**Comment by milanglacier** [comment]
> Hey I made some fix for inserting icons: [c05ba48](https://github.com/rainstormstudio/nerd-icons-dired/commit/c05ba4815d375d779644ca7ac215632fda75089c)
> 
> Could you please try this and see if it works for `wdired-mode`?

It works for wdired-mode. But not for overlapped tab indicator sign. Indeed I don't think there's much thing we can do, since nerd icons takes two characters width for some fonts but only one character width for some fonts.

**Comment by rainstormstudio** [comment]
It shouldn't be affected by character width though. The thing is, Nerd icons shouldn't use overlays as they are texts not images. By using `insert`, it fixes other issues.

Which platform are you using Emacs with? Could you please provide a screenshot for current state? I think it's better to fix your issue using `insert` instead of avoiding `global-whitespace-mode`

**Comment by milanglacier** [comment]
I used macoS.

This is what dired-nerd-icons looks like with global-whitespace-mode

<img width="660" alt="Screenshot 2023-04-29 at 10 40 12" src="https://user-images.githubusercontent.com/45728125/235308594-673a6edc-12ed-4ad5-a324-880c8cf0e0a0.png">

**Comment by rainstormstudio** [comment]
yes so on MacOS, if you are using GUI, I recommend using the default "Symbols Nerd Font Mono". Because of how MacOS dealing with rendering icons, the variable width of icons is ignored somehow. By using "Symbols Nerd Font Mono", it ensures the width of icons is recognized by the system.

**Comment by milanglacier** [comment]
Yes this is true, on macOS GUI the best way is to use the default Symbol Nerd Font Mono, by calling `(nerd-icons-install-fonts)`.

The symbol nerd font font displays perfectly in macos GUI.
