### ISSUE TITLE
nerd-icons-dired does not support `set-rectangular-region-anchor` + `kill-region` under `wdired` enabled Dired buffer

### ISSUE THREAD

**Issue by stardiviner** [rainstormstudio/nerd-icons-dired#5]
When I try to enable wdired on nerd-icons-dired minor mode enabled Dired buffer. I edit dired buffer will got error. file read-only. I hope this package can support "set-rectangular-region-anchor" in `wdired-change-to-wdired-mode`.

**Comment by stardiviner** [comment]
After I dive into source code:

- nerd-icons-dired implemented using *text-property*: https://github.com/rainstormstudio/nerd-icons-dired/blob/main/nerd-icons-dired.el#L84

- all-the-icons implemented using *overlay*: https://github.com/jtbm37/all-the-icons-dired/blob/master/all-the-icons-dired.el#L55

**Comment by rainstormstudio** [comment]
We changed to *text-property* a few days ago as *overlay* is not the proper way of using font icons like nerd-icons. 

I'll take a look at wgrep and try to fix this.

**Comment by stardiviner** [comment]
Thanks.

**Comment by milanglacier** [comment]
Wdired mode in my computer works fine. What does using wgrep on dired buffer mean?
I am on the commit  c05ba4815d375d779644ca7ac215632fda75089c.

**Comment by stardiviner** [comment]
@milanglacier You're right, I'm confused [C-c C-p] keybinding for `wgrep` and `wdired`. Now I updated issue title.

I recorded a video to reproduce my error when using `wdired` in Dired buffer with `nerd-icons-dired` buffer.

[recorded video](https://upload.disroot.org/r/VpcBBCxJ#hhozOcuiOC97K/+wBCoG35W7D5faf5nspMokAEP0zzQ=)

**Comment by rainstormstudio** [comment]
Thanks for the detailed video! I think it's because I set the icons to be readonly in the buffer. I'll look into this.

**Comment by stardiviner** [comment]
@rainstormstudio Any idea update about this problem?

**Comment by rainstormstudio** [comment]
I'll be moving back to overlays but before I do so I need to fix some bugs related to overlays.

**Comment by stardiviner** [comment]
The text-property can't be inserted without read-only property? Maybe Emacs-dev mailing list has some idea?

**Comment by rainstormstudio** [comment]
no it's dired who has read-only property already so I cannot insert the icons directly

**Comment by stardiviner** [comment]
I see, thanks for explaination.

**Comment by stardiviner** [comment]
The issue is fixed, close now. Thanks @rainstormstudio
